### ISSUE TITLE
error: Schema must be an instance of GraphQLSchema....

### ISSUE THREAD

**Issue by beebase** [arangodb/graphql-sync#10]
I copied the demo-graphql service to my local disk, renamed it, added npm graphql-sync + node_modules folder, uploaded again.
Now I'm getting this error when trying to connect to the new foxx service with graphiql.
Could this be related to version 0.10.1 of graphql-js ?

```
{
  "errors": [
    {
      "message": "Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory."
    }
  ]
}

**Comment by pilot4u** [comment]
I'm struggling with the same issue,
tried this post as well, https://www.arangodb.com/2017/10/auto-generate-graphql-arangodb/
but there I'm getting following error:
ArangoError: failed to invoke module
File: /var/lib/arangodb3-apps/_db/_system/graphql/APP/main.js
Cause: TypeError: db._parse is not a function
at objectDefinition.fields.forEach.field (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/generateResolveFunctions.js:62:38)
at Array.forEach (native)
at ast.definitions.forEach.objectDefinition (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/generateResolveFunctions.js:49:31)
at Array.forEach (native)
at module.exports (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/generateResolveFunctions.js:6:19)
at _generateSchema (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/index.js:81:3)
at makeExecutableSchema (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/index.js:52:20)
at module.exports (/var/lib/arangodb3-apps/_db/_system/graphql/APP/node_modules/graphql-aql-generator/index.js:264:32)
at Object.<anonymous> (/var/lib/arangodb3-apps/_db/_system/graphql/APP/main.js:28:16)
at Module._compile (/usr/share/arangodb3/js/common/bootstrap/modules.js:586:8)
at Module.load (/usr/share/arangodb3/js/common/bootstrap/modules.js:542:23)
at FoxxService.run (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/service.js:430:14)
at exports.routeService (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/routing.js:153:40)
at Object.routes (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:283:10)
at foxxRouting (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:999:74)
at execute (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1241:7)
at Object.routeRequest (/usr/share/arangodb3/js/server/modules/@arangodb/actions.js:1260:3)
at Function.actions.defineHttp.callback (/usr/share/arangodb3/js/actions/api-system.js:54:15)

I'll be more the happy if anybody could upload a working solution for graphql with arangoDb
